### ISSUE TITLE
Drop setup.py?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-lsl#165]
I believe you can simply remove `setup.py` now. Not tested, but it should just work without it since you're specifying a fairly new version of setuptools in `pyproject.toml`, which should be able to handle this.

**Comment by mscheltienne** [comment]
Will check and drop if able!

**Comment by mscheltienne** [comment]
From reading (without testing) I think I need to bump to `setuptools 64.0.0` which added support for PEP 660 and editable installs.

**Comment by hoechenberger** [comment]
I thought we had it working with older setuptools versions too (52 or so). But I'd need to check. 

But since you can specify which setuptools version is needed for build & installation, I believe it's not an issue simply requiring 0.64 just to be sure
