### ISSUE TITLE
Add parameter to stop player_lsl when data was finished iterating

### ISSUE THREAD

**Issue by timonmerk** [mne-tools/mne-lsl#220]
First, many thanks for providing this super useful tool! The speed improvement over pylsl is really amazing!

I have a small discussion point. It would be great to provide a parameter to player_lsl that terminates the stream once it finishes running through the data once.

I think it would be simply terminating the stream once it passes this condition: https://github.com/mne-tools/mne-lsl/blob/948235dcfad54774611053331ad6dce17e65479a/mne_lsl/player/player_lsl.py#L244 
Probably there were also good reasons to repeat the stream, but for offline and  online equivalent analyses that would be a useful feature!

**Comment by mscheltienne** [comment]
Sure, I removed this parameter/possibility at some point, but I can add it back if there is a need.
Does a `n_repeat: Optional[int] = None` argument sounds good to you, where `None` loops infintely, `n_repeat = int` loops the number of times requested (1 in your usecase)?

**Comment by timonmerk** [comment]
That sounds great! Thanks!

**Comment by mscheltienne** [comment]
@timonmerk Released in 1.3.0 today!
