### ISSUE TITLE
Re-enable test in CIs when noble build of LSL is available

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-lsl#345]
PR #343 skips a test on linux CIs since ubuntu-latest updated to 24.04 LTS and LSL did not yet release a 24.04 build.

https://github.com/mne-tools/mne-lsl/blob/59a221f153054e418e2f3ed2c72eb5f7334ce8dc/mne_lsl/lsl/tests/test_load_liblsl.py#L77-L80

depends on: 
- https://github.com/sccn/liblsl/issues/223

**Comment by larsoner** [comment]
Just thinking out loud... is there a reason we don't make `mne-lsl` a `cibuildwheel` project and compile `liblsl` ourselves using `abi3`? It's a bit more maintenance overhead but I'm not sure why LSL needs to build for different platforms. [`cffi`](https://cffi.readthedocs.io/en/stable/) might make this pretty easy (it even sets the ABI flags during compilation), it's what is used in [`python-rtmixer`](https://github.com/spatialaudio/python-rtmixer) for example.

**Comment by larsoner** [comment]
> I don't know if we would need platform-specific wheels.

Yeah we would if we bundled `liblsl` but I think that could be okay. I might give it a shot and see how bad it is
